chore(deps): update all non-major dependencies (#211)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@shufo/prettier-plugin-blade](https://redirect.github.com/shufo/prettier-plugin-blade)
| [`^1.15.1` ->
`^1.15.2`](https://renovatebot.com/diffs/npm/@shufo%2fprettier-plugin-blade/1.15.1/1.15.2)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@shufo%2fprettier-plugin-blade/1.15.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@shufo%2fprettier-plugin-blade/1.15.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@shufo%2fprettier-plugin-blade/1.15.1/1.15.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@shufo%2fprettier-plugin-blade/1.15.1/1.15.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/node](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node))
| [`^20.17.14` ->
`^20.17.16`](https://renovatebot.com/diffs/npm/@types%2fnode/20.17.14/20.17.16)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/20.17.14/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/20.17.14/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [lint-staged](https://redirect.github.com/lint-staged/lint-staged) |
[`^15.4.1` ->
`^15.4.3`](https://renovatebot.com/diffs/npm/lint-staged/15.4.1/15.4.3)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lint-staged/15.4.1/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lint-staged/15.4.1/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[prettier-plugin-classnames](https://redirect.github.com/ony3000/prettier-plugin-classnames)
| [`^0.7.5` ->
`^0.7.6`](https://renovatebot.com/diffs/npm/prettier-plugin-classnames/0.7.5/0.7.6)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier-plugin-classnames/0.7.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier-plugin-classnames/0.7.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier-plugin-classnames/0.7.5/0.7.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier-plugin-classnames/0.7.5/0.7.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[prettier-plugin-tailwindcss](https://redirect.github.com/tailwindlabs/prettier-plugin-tailwindcss)
| [`^0.6.10` ->
`^0.6.11`](https://renovatebot.com/diffs/npm/prettier-plugin-tailwindcss/0.6.10/0.6.11)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier-plugin-tailwindcss/0.6.11?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier-plugin-tailwindcss/0.6.11?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier-plugin-tailwindcss/0.6.10/0.6.11?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier-plugin-tailwindcss/0.6.10/0.6.11?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [remeda](https://remedajs.com/)
([source](https://redirect.github.com/remeda/remeda)) | [`^2.19.2` ->
`^2.20.0`](https://renovatebot.com/diffs/npm/remeda/2.19.2/2.20.0) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/remeda/2.20.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/remeda/2.20.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/remeda/2.19.2/2.20.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/remeda/2.19.2/2.20.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [tsup](https://tsup.egoist.dev/)
([source](https://redirect.github.com/egoist/tsup)) | [`^8.3.5` ->
`^8.3.6`](https://renovatebot.com/diffs/npm/tsup/8.3.5/8.3.6) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/tsup/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/tsup/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/tsup/8.3.5/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/tsup/8.3.5/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>shufo/prettier-plugin-blade
(@&#8203;shufo/prettier-plugin-blade)</summary>

###
[`v1.15.2`](https://redirect.github.com/shufo/prettier-plugin-blade/blob/HEAD/CHANGELOG.md#1152-2025-01-25)

[Compare
Source](https://redirect.github.com/shufo/prettier-plugin-blade/compare/v1.15.1...v1.15.2)

##### Miscellaneous

- 🤖 bump blade-formatter to 1.42.1
([94ce0af](https://redirect.github.com/shufo/prettier-plugin-blade/commit/94ce0af371f4d79f3dce922b0d8df8012d585b08))
- **deps:** update dependency vitest to v3
([a3ea4b3](https://redirect.github.com/shufo/prettier-plugin-blade/commit/a3ea4b36c2884194733321c03cedefdf2b65d5d4))

</details>

<details>
<summary>lint-staged/lint-staged (lint-staged)</summary>

###
[`v15.4.3`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1543)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.2...v15.4.3)

##### Patch Changes

-
[#&#8203;1512](https://redirect.github.com/lint-staged/lint-staged/pull/1512)
[`cbfed1d`](https://redirect.github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1)
Thanks [@&#8203;tarik02](https://redirect.github.com/tarik02)! - Adjust
TypeScript types for the default export so that it can be used as a
value without error TS2693.

###
[`v15.4.2`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1542)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.1...v15.4.2)

##### Patch Changes

-
[#&#8203;1509](https://redirect.github.com/lint-staged/lint-staged/pull/1509)
[`8827ebf`](https://redirect.github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Change
*lint-staged*'s dependencies to use [caret (`^`)
ranges](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)
instead of [tilde
(`~`)](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1).
This makes it easier for package managers to perform dependency
management when minor-level updates are also permitted instead of just
patch-level.

</details>

<details>
<summary>ony3000/prettier-plugin-classnames
(prettier-plugin-classnames)</summary>

###
[`v0.7.6`](https://redirect.github.com/ony3000/prettier-plugin-classnames/releases/tag/v0.7.6)

[Compare
Source](https://redirect.github.com/ony3000/prettier-plugin-classnames/compare/v0.7.5...v0.7.6)

#### What's Changed

- Handles cases where square brackets are required in single-line object
properties by [@&#8203;ony3000](https://redirect.github.com/ony3000) in
[https://github.com/ony3000/prettier-plugin-classnames/pull/84](https://redirect.github.com/ony3000/prettier-plugin-classnames/pull/84)
- Print the message of the caught error in the second format by
[@&#8203;ony3000](https://redirect.github.com/ony3000) in
[https://github.com/ony3000/prettier-plugin-classnames/pull/85](https://redirect.github.com/ony3000/prettier-plugin-classnames/pull/85)
- Ensures that line wrapping only occur on the last operand in logical
expressions by [@&#8203;ony3000](https://redirect.github.com/ony3000) in
[https://github.com/ony3000/prettier-plugin-classnames/pull/86](https://redirect.github.com/ony3000/prettier-plugin-classnames/pull/86)
- Further improves formatting of nested expressions by
[@&#8203;ony3000](https://redirect.github.com/ony3000) in
[https://github.com/ony3000/prettier-plugin-classnames/pull/87](https://redirect.github.com/ony3000/prettier-plugin-classnames/pull/87)

**Full Changelog**:
https://github.com/ony3000/prettier-plugin-classnames/compare/v0.7.5...v0.7.6

</details>

<details>
<summary>tailwindlabs/prettier-plugin-tailwindcss
(prettier-plugin-tailwindcss)</summary>

###
[`v0.6.11`](https://redirect.github.com/tailwindlabs/prettier-plugin-tailwindcss/blob/HEAD/CHANGELOG.md#0611---2025-01-23)

[Compare
Source](https://redirect.github.com/tailwindlabs/prettier-plugin-tailwindcss/compare/v0.6.10...v0.6.11)

- Support TypeScript configs and plugins when using v4
([#&#8203;342](https://redirect.github.com/tailwindlabs/prettier-plugin-tailwindcss/pull/342))

</details>

<details>
<summary>remeda/remeda (remeda)</summary>

###
[`v2.20.0`](https://redirect.github.com/remeda/remeda/releases/tag/v2.20.0)

[Compare
Source](https://redirect.github.com/remeda/remeda/compare/v2.19.2...v2.20.0)

##### Features

- **mergeAll:** Create more specific return type for mergeAll
([#&#8203;1002](https://redirect.github.com/remeda/remeda/issues/1002))
([8c0e22b](https://redirect.github.com/remeda/remeda/commit/8c0e22bb0fc1b2f279ddb9bc04abce89fdbc62a2)),
closes
[#&#8203;918](https://redirect.github.com/remeda/remeda/issues/918)
[#&#8203;1006](https://redirect.github.com/remeda/remeda/issues/1006)

</details>

<details>
<summary>egoist/tsup (tsup)</summary>

###
[`v8.3.6`](https://redirect.github.com/egoist/tsup/releases/tag/v8.3.6)

[Compare
Source](https://redirect.github.com/egoist/tsup/compare/v8.3.5...v8.3.6)

#####    🐞 Bug Fixes

- Don't await sub-process of `onSuccess`  -  by
[@&#8203;laat](https://redirect.github.com/laat) in
[https://github.com/egoist/tsup/issues/1256](https://redirect.github.com/egoist/tsup/issues/1256)
[<samp>(314a6)</samp>](https://redirect.github.com/egoist/tsup/commit/314a6d7)

#####     [View changes on
GitHub](https://redirect.github.com/egoist/tsup/compare/v8.3.5...v8.3.6)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "after 2am and before 3am" in timezone
Asia/Shanghai, Automerge - "schedule:daily" in timezone Asia/Shanghai.

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/u3u/prettier-config).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMjUuMSIsInVwZGF0ZWRJblZlciI6IjM5LjEyNS4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>